graph TD
  %% Application Routes
  Root[/] --> Pages

    Pages --> route_["/"]
  Pages --> route_architecture["/architecture"]
  Pages --> route_projects["/projects"]
  Pages --> route_404["/404"]
  Pages --> route_contact["/contact"]
  Pages --> route_about["/about"]

  style Root fill:#2563EB,color:#fff
  style Pages fill:#7C3AED,color:#fff
